version: "3.4"
services:
  dshackle:
    image: "dshackle.dshackle.public.dappnode.eth:0.2.0"
    build:
      context: build
      args:
        UPSTREAM_VERSION: 0.11.1
    volumes:
      - "dshackle:/etc/dshackle"
    environment:
      - INFURA_KEY=
      - RIVET_KEY=
      - ALCHEMY_KEY=
    restart: unless-stopped
volumes:
  dshackle: {}
