version: "3.5"
services:
  dshackle:
    image: dshackle.dshackle.public.dappnode.eth:0.6.0
    build:
      context: build
      args:
        UPSTREAM_VERSION: 0.15.1
    volumes:
      - dshackle:/etc/dshackle
    environment:
      - LOCALNODE_HTTP=http://geth.dappnode:8545
    restart: unless-stopped
volumes:
  dshackle: {}
