version: "3.4"
services:
  dshackle:
    image: "dshackle.dshackle.public.dappnode.eth:0.3.0"
    build:
      context: build
      args:
        UPSTREAM_VERSION: 0.13.0
    volumes:
      - "dshackle:/etc/dshackle"
    environment:
      - "LOCALNODE_HTTP=http://geth.dappnode:8545"
    restart: unless-stopped
volumes:
  dshackle: {}
